"""Init db

Revision ID: 671e1de3b3f6
Revises: 
Create Date: 2024-11-19 16:10:25.819425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671e1de3b3f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beat_id'), 'beat', ['id'], unique=False)
    op.create_table('vocal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('beat_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocal_id'), 'vocal', ['id'], unique=False)
    op.create_table('music',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vocal_id', sa.Uuid(), nullable=False),
    sa.Column('beat_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beat.id'], ),
    sa.ForeignKeyConstraint(['vocal_id'], ['vocal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_id'), 'music', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_id'), table_name='music')
    op.drop_table('music')
    op.drop_index(op.f('ix_vocal_id'), table_name='vocal')
    op.drop_table('vocal')
    op.drop_index(op.f('ix_beat_id'), table_name='beat')
    op.drop_table('beat')
    # ### end Alembic commands ###

import sqlalchemy as sa
import sqlmodel
