"""Update Vocal

Revision ID: 81521d0667aa
Revises: 671e1de3b3f6
Create Date: 2024-11-19 17:03:00.803968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81521d0667aa'
down_revision = '671e1de3b3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocal', 'img_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocal', sa.Column('img_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

import sqlalchemy as sa
import sqlmodel
