"""Add img

Revision ID: 99557d962b1d
Revises: 601dba411951
Create Date: 2024-11-18 15:23:57.134451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99557d962b1d'
down_revision = '601dba411951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'img_path')
    # ### end Alembic commands ###

import sqlalchemy as sa
import sqlmodel
