"""Update Music model

Revision ID: d74d06d45e11
Revises: 81521d0667aa
Create Date: 2024-11-21 17:27:54.932777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74d06d45e11'
down_revision = '81521d0667aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'vocal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('music', 'beat_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'beat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('music', 'vocal_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

import sqlalchemy as sa
import sqlmodel
